import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn, signOut, useSession } from "next-auth/client";
import { useState, useEffect } from "react";
import axios from "axios";

export default function Home() {
  const [session] = useSession();
  const [following, setFollowing] = useState();
  const getAndSetData = async () => {
    const users = await axios
      .get("api/twitter/following")
      .then((res) => res.data.data.users);
    setFollowing(users);
  };

  useEffect(() => {
    getAndSetData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session && (
          <>
            <p>Not signed in</p>
            <button onClick={() => signIn()}>Sign In</button>
          </>
        )}
        {session && (
          <>
            Signed in as {session.user.email}
            {following?.map((user) => {
              return <p>{user.name}</p>;
            })}
            <button onClick={() => signOut()}>Sign Out</button>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
